import Foundation

extension SelfTest {
    /// SelfTest's own checks from 108, run straight after `earlierCoreTests`.
    static var laterCoreTests: [(String, () -> [String])] {
        [
            ("An unlocked absence past the cap still ends the session",
             testUnlockedAbsenceEndsSession),
            ("Hands-on time inside a paused session cannot fill the goal",
             testGoalDistractionCap),
            ("A night that began idle and then locked still ends the session",
             testIdleThenLockedNightEndsSession),
            ("A second absence the card sat through survives a relaunch",
             testShadowAwaySurvivesRelaunch),
            ("Sessions, Focused and Longest follow the selected day",
             testDayScopedSessionFigures),
            ("Historical goal status uses focused-active time",
             testHistoricalGoalStatusUsesFocusedActiveTime),
            ("Palette: seven distinct app colours, both appearances, total work types",
             testPalette),
            ("Menu-bar glyph renders a template ring for every state", testMenuBarGlyph),
            ("Settings model writes through and notifies once per change", testSettingsModel),
            ("Reveal data folder creates pristine storage and reports failures",
             testRevealDataFolderWorkflow),
            ("Previous-period total is the same rollup one period back",
             testPreviousPeriodTracked),
            ("The popover still fits a 13\" screen with the away card up",
             testPopoverStillFits13Inch),
            ("Away prompt tier is a pure rule; Never means quick", testAwayPromptTier),
            ("Pending away range spans the absence and ends at return", testPendingAwayRange),
            ("The hero clock is the thread's, picking up after a break", testThreadClock),
            ("Coming back in a different app starts new work; same app continues",
             testAppAwareContinuity),
            ("Rhythm: segments split across hours, dominant app per hour, peak run",
             testRhythm),
            ("A named break is recorded under that name; other answers ignore it",
             testNamedBreak),
            ("Day digest: stretches fold by thread, breaks sit between, running joins",
             testSessionDigest),
            ("Day digest and focus metrics stay clipped to the selected day",
             testDayDigestAndFocusAreDayScoped),
            ("Live focus quality clips running work at midnight",
             testLiveFocusQualityClipsAtMidnight),
            ("Apps within a session's spans: intersected, ranked, shares of the inside",
             testAppsWithinSpans),
            ("Summary text: every clause gated on its figure; empty days say so",
             testSummaryText),
            ("Sessions are threads: stretches of one thread count once, running included",
             testSessionsAreThreads),
            ("An absence is measured from where it began, not from a late idle pause",
             testAbsenceFromWhereItBegan),
            ("Relaunched behind a lock, the absence stays open until the unlock",
             testRestoreBehindLock),
            ("The menu bar's band stays on today while the dashboard browses",
             testGlanceStaysOnToday),
            ("Watching is presence: quiet pause, written down, never asked about; meetings count",
             testWatchingIsNotAbsence),
            ("Quiet while a question is pending is an absence the card sat through",
             testQuietWhileAwaiting),
            ("Declared categories are a last resort; automatic sessions are named",
             testCategoryFallbackAndNames),
            ("A wake is the machine's: only input or an unlock ends an absence",
             testWakeIsNotAReturn),
            ("Main navigation and interface preferences persist across reload",
             testMainNavigationAndInterfacePreferences),
            ("System appearance clears an explicit application override",
             testSystemAppearanceClearsApplicationOverride),
            ("Warm-precision design tokens preserve practical density and semantic signals",
             testWarmPrecisionDesignTokensAndDensity),
            ("Main-window deep links and commands select their exact routes",
             testMainWindowRoutesAndCommands),
            ("Unified window chrome keeps context beside tabs without a native focus ring",
             testUnifiedWindowChrome),
            ("Review keeps tracked bars canonical and History filters by intersection",
             testReviewHistoryFiltersAndDayRouting),
            ("A selected Review day derives canonical, day-scoped detail",
             testReviewSelectedDayDetail),
            ("Selecting or clearing a Review day stays in Review",
             testReviewContentHierarchy),
            ("Focus stays an instrument",
             testDayAndFocusHierarchy),
            ("Insights lead with the finding; Settings keeps a native measure",
             testInsightAndSettingsPresentation),
            ("Awards are earned from the record, never invented",
             testAwardsAreEvidenceBacked),
            ("Insights render statements only when canonical evidence exists",
             testInsightSurfaceRequiresEvidence),
            ("Insights rhythm and active days exclude pre-accuracy usage",
             testInsightsExcludePreAccuracyUsage),
            ("Insights quality deduplicates resumed threads across its full range",
             testInsightQualityDeduplicatesThreadsAcrossRange),
            ("Tracker checkpoints refresh visible and next-open Insights",
             testTrackerTransitionsInvalidateInsights),
            ("Insights preserve tiny positive quality facts without zero labels",
             testInsightQualityPreservesTinyPositiveEvidence),
            ("Period logs retain the newest 500 sessions consistently",
             testPeriodLogRetainsNewestLimit),
            ("Selected Review days retain app evidence beyond the period-log cap",
             testReviewDetailRetainsUncappedDayEntries),
            ("Review keeps focus-only periods out of the empty state",
             testReviewFocusOnlyPeriodEvidence),
            ("Dense focus Review shows the newest 500 rows without capping evidence",
             testReviewFocusRowsAreBoundedAndQualified),
            ("History query matches the displayed app name",
             testHistorySearchesDisplayedAppName),
            ("History bounds malformed spans but keeps ordinary midnight clipping",
             testHistoryBoundsMalformedSpans),
            ("History discloses legacy accuracy and span-bound derived omissions",
             testHistoryDisclosesLegacyAndDroppedSpans),
            ("Review longest focus clips period boundaries and excludes breaks",
             testReviewLongestFocusClipsBoundsAndExcludesBreaks),
            ("Timeline rests stay clipped inside otherwise unknown gaps",
             testTimelineRestEvidenceStaysCanonical),
            ("Focus states keep one honest action and continuations stop at three",
             testFocusSurfaceStateAndContinuationLimit),
            ("Focus composition guards decisions and keeps automatic corrections available",
             testFocusSurfaceCompositionGuards),
            ("Unresolved Away decisions reject ordinary session mutations",
             testAwayDecisionRejectsOrdinarySessionMutations),
            ("The global hotkey routes unresolved Away evidence to its decision surface",
             testHotKeyRoutesPendingAwayDecision),
            ("Sessions per app limits the real Today app-session list",
             testSessionsPerAppLimitsProductionAppHistory),
            ("Focus quality counts threads and real app transitions",
             testFocusQualityCountsThreadsAndTransitions),
            ("Declared-Away automatic corrections resume tracking exactly once",
             testDeclaredAwayAutomaticCorrectionRoutes),
            ("Settings groups contain only backed controls",
             testSettingsGroupsContainOnlyBackedControls),
            ("The story's corrections reach the day it shows",
             testStoryCorrectionsReachTheDay),
            ("A stored tile order is repaired, never trusted verbatim",
             testStoredTileOrderIsRepaired),
            ("Correcting a session rewrites its whole thread",
             testCorrectingASessionRewritesItsThread),
            ("A session's shape reports only what was recorded",
             testSessionShapeReportsOnlyRecordedEvidence),
            ("Unrecorded focus is the focused span usage never saw",
             testUnrecordedFocusIsTheUncoveredSpan),
            ("The window opens on the day's story, and a sheet route on its sheet",
             testWindowOpensOnPreferredStory),
            ("Narrative diagnostics use a full-width status layout",
             testSettingsDiagnosticLayout),
            ("Settings privacy distinguishes monitoring from entered session data",
             testSettingsPrivacyDisclosure),
            ("Shared panels consume the interface density environment",
             testSharedPanelDensityEnvironment),
            ("Settings accuracy epoch always includes its year",
             testSettingsAccuracyEpochYear),
            ("Compact Focus snapshots retain the title and status band",
             testCompactFocusSnapshotStructure),
            ("Accessible navigation and charts expose literal selected-state evidence",
             testAccessibleNavigationAndChartSummaries),
            ("Snapshot matrix covers every material surface",
             testSnapshotMatrixCoversEveryMaterialSurface),
            ("Simultaneous snapshots keep isolated presentation preferences",
             testSimultaneousSnapshotsKeepIsolatedPreferences),
            ("Away snapshots retain production prompt chrome",
             testAwaySnapshotsRetainProductionPromptChrome)
        ]
    }
}
