import Foundation
import SwiftUI
import Combine
import AppKit

extension SelfTest {
    /// App notifications can arrive between wake and the confirming HID reset.
    /// They update which app is waiting, but the notification itself is not
    /// permission to record; ordinary stopped activation remains immediate.
    static func testWaitingActivationUpdatesCandidate() -> [String] {
        var problems: [String] = []
        let clock = TestClock(base)
        let directory = scratchDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }
        let usage = AppUsageArchive(directory: directory, now: { clock.value })
        let tracker = AppUsageTracker(archive: usage,
                                      ownBundleID: FocusConstants.bundleIdentifier,
                                      idle: .disabled,
                                      now: { clock.value })

        tracker.prepareToResume(bundleID: "com.example.editor", name: "Editor")
        clock.advance(10)
        tracker.appActivated(bundleID: "com.example.browser", name: "Browser")
        clock.advance(30)
        tracker.flush()
        expect(tracker.currentBundleID == nil && tracker.isObserving,
               "activation while waiting must remain non-recording", &problems)
        expect(usage.sessions.isEmpty,
               "a waiting activation must not create an app-usage record", &problems)

        let confirmedAt = clock.value
        tracker.confirmPresence(at: confirmedAt)
        expect(tracker.currentBundleID == "com.example.browser",
               "confirmation starts the updated candidate app", &problems)
        clock.advance(60)
        tracker.flush()
        expect(usage.sessions.count == 1
                   && usage.sessions.first?.bundleID == "com.example.browser"
                   && usage.sessions.first?.appName == "Browser",
               "only the updated candidate is recorded after confirmation", &problems)
        expectClose(usage.sessions.first?.start.timeIntervalSince(confirmedAt) ?? -1, 0,
                    "the updated candidate starts at confirmation", &problems)

        let ordinaryDirectory = scratchDirectory()
        defer { try? FileManager.default.removeItem(at: ordinaryDirectory) }
        let ordinary = AppUsageTracker(
            archive: AppUsageArchive(directory: ordinaryDirectory, now: { clock.value }),
            ownBundleID: FocusConstants.bundleIdentifier,
            idle: .disabled,
            now: { clock.value })
        ordinary.appActivated(bundleID: "com.example.terminal", name: "Terminal")
        expect(ordinary.currentBundleID == "com.example.terminal",
               "ordinary stopped activation must still begin immediately", &problems)
        return problems
    }

    /// A workspace activation can be generated by the machine while a display
    /// wakes. Until presence is confirmed it may update only the pending app;
    /// otherwise an idle engine starts work, a paused one resumes, and the auto
    /// detector evaluates evidence nobody produced.
    static func testWakeActivationDefersEngineAndAutomation() -> [String] {
        var problems: [String] = []

        func makeContext() -> (TestClock, SessionEngine, SessionStore, AppUsageTracker) {
            let clock = TestClock(base)
            let directory = scratchDirectory()
            let defaults = MemoryDefaults.suite(named: suiteName) ?? .standard
            let persistence = PersistenceStore(defaults: defaults)
            persistence.removeAll()
            let engine = SessionEngine(
                store: persistence,
                archive: SessionArchive(directory: directory, now: { clock.value }),
                ownBundleID: "com.example.self", schedulesDwell: false,
                now: { clock.value })
            let usage = AppUsageArchive(directory: directory, now: { clock.value })
            let tracker = AppUsageTracker(archive: usage, ownBundleID: "com.example.self",
                                          idle: .disabled, now: { clock.value })
            let store = SessionStore(engine: engine)
            store.attach(tracker: tracker, usage: usage)
            return (clock, engine, store, tracker)
        }

        do {
            let (clock, engine, store, tracker) = makeContext()
            var automationRuns = 0
            store.onDeferredAutomationReady = { automationRuns += 1 }
            store.noteMachineWake()
            tracker.prepareToResume(bundleID: "com.apple.dt.Xcode", name: "Xcode")

            let firstDelivered = store.handleApplicationActivation(
                bundleID: "com.apple.dt.Xcode", name: "Xcode")
            let latestDelivered = store.handleApplicationActivation(
                bundleID: "com.microsoft.VSCode", name: "Visual Studio Code")
            store.prepareTrackingResume(bundleID: "com.apple.dt.Xcode", name: "Xcode")
            expect(!firstDelivered && !latestDelivered,
                   "wake-suppressed activations must report themselves deferred", &problems)
            expect(engine.state == .idle && engine.currentAppBundleID == nil,
                   "a machine activation must not start an idle engine", &problems)
            expect(tracker.currentBundleID == nil && automationRuns == 0,
                   "neither usage nor automation may start before presence", &problems)

            store.confirmPresence(at: clock.value)
            expect(engine.state == .running
                       && engine.currentAppBundleID == "com.apple.dt.Xcode",
                   "confirmation delivers the latest prepared frontmost activation", &problems)
            expect(tracker.currentBundleID == "com.apple.dt.Xcode",
                   "the tracker confirms the same latest prepared app", &problems)
            expect(automationRuns == 1,
                   "deferred automation runs exactly once after confirmation", &problems)
            store.confirmPresence(at: clock.value)
            expect(automationRuns == 1,
                   "repeated confirmation cannot replay deferred automation", &problems)
        }

        do {
            let (clock, engine, store, tracker) = makeContext()
            engine.start(workType: .deepWork, intent: "Manual")
            engine.transition(on: .manualPause)
            store.noteMachineWake()
            tracker.prepareToResume(bundleID: "com.apple.dt.Xcode", name: "Xcode")
            let delivered = store.handleApplicationActivation(
                bundleID: "com.apple.dt.Xcode", name: "Xcode")
            expect(!delivered && engine.state == .paused(reason: .manual),
                   "a wake activation must not resume a deliberate pause", &problems)
            store.confirmPresence(at: clock.value)
            expect(engine.state == .running,
                   "the deferred work activation resumes only after presence", &problems)
        }

        do {
            let (clock, engine, store, tracker) = makeContext()
            engine.restore(from: PersistedState(
                state: .running, name: "Automatic", sessionStart: clock.value,
                totalPaused: 0, pauseStart: nil, away: nil, lastApp: "—",
                lastAppBundleID: nil, decisionStarted: nil, savedAt: clock.value,
                threadID: UUID(), isAuto: true))
            var automationRuns = 0
            store.onDeferredAutomationReady = { automationRuns += 1 }
            store.noteMachineWake()
            tracker.prepareToResume(bundleID: "com.apple.dt.Xcode", name: "Xcode")
            _ = store.handleApplicationActivation(bundleID: "com.apple.dt.Xcode",
                                                  name: "Xcode")
            expect(engine.currentAppBundleID == nil && engine.activeIsAuto,
                   "a running automatic session receives no machine activation", &problems)
            expect(automationRuns == 0,
                   "the automatic detector remains gated while presence is unknown", &problems)
            store.confirmPresence(at: clock.value)
            expect(engine.currentAppBundleID == "com.apple.dt.Xcode" && engine.activeIsAuto,
                   "confirmation delivers the activation without changing auto ownership",
                   &problems)
            expect(automationRuns == 1,
                   "the automatic path evaluates once after genuine presence", &problems)
        }

        return problems
    }

    /// Wake preparation can legitimately find no ordinary frontmost app. A
    /// later workspace activation is still machine evidence, not permission for
    /// a stopped tracker to begin before the shared presence gate confirms it.
    static func testUnpreparedWakeActivationRemainsGated() -> [String] {
        var problems: [String] = []
        let clock = TestClock(base)
        let directory = scratchDirectory()
        let usage = AppUsageArchive(directory: directory, now: { clock.value })
        let tracker = AppUsageTracker(archive: usage, ownBundleID: "com.example.self",
                                      idle: .disabled, now: { clock.value })
        let engine = makeEngine(clock)
        let store = SessionStore(engine: engine, now: { clock.value })
        store.attach(tracker: tracker, usage: usage)

        store.noteMachineWake()
        let delivered = store.handleApplicationActivation(
            bundleID: "com.example.editor", name: "Editor")
        clock.advance(60)
        tracker.flush()

        expect(!delivered && tracker.currentBundleID == nil,
               "an unprepared wake activation must remain a waiting candidate", &problems)
        expect(usage.sessions.isEmpty,
               "an unprepared wake activation records nothing before presence", &problems)

        let confirmedAt = clock.value
        store.confirmPresence(at: confirmedAt)
        clock.advance(60)
        tracker.flush()
        expectClose(usage.sessions.first?.start.timeIntervalSince(confirmedAt) ?? -1, 0,
                    "usage begins at confirmed presence rather than machine activation", &problems)
        expectClose(usage.sessions.first?.seconds ?? -1, 60,
                    "only post-confirmation usage is retained", &problems)
        return problems
    }

    /// Initial frontmost-app seeding is permitted only when the display can
    /// actually be in front of a person. An unlocked but sleeping display is as
    /// absent as a locked one and must wait for later presence evidence.
    static func testLaunchUsageSeedRequiresVisiblePresence() -> [String] {
        var problems: [String] = []
        let cases: [(locked: Bool, asleep: Bool, expected: Bool, label: String)] = [
            (false, false, true, "unlocked and awake"),
            (true, false, false, "locked and awake"),
            (false, true, false, "unlocked and asleep"),
            (true, true, false, "locked and asleep")
        ]
        for item in cases {
            let actual = AppCoordinator.permitsInitialUsageSeed(
                screenLocked: item.locked, displayAsleep: item.asleep)
            expect(actual == item.expected,
                   "launch seed policy for \(item.label) expected \(item.expected), got \(actual)",
                   &problems)
        }
        return problems
    }

    /// A due break is said once: on the HUD when someone can see this display,
    /// as a notification when they cannot. Any one absence is enough to send
    /// it to Notification Centre instead.
    static func testBreakReminderUsesOneChannel() -> [String] {
        var problems: [String] = []
        let cases: [(locked: Bool, asleep: Bool, sleeping: Bool, away: Bool, expected: Bool, label: String)] = [
            (false, false, false, false, true, "present"),
            (true, false, false, false, false, "locked"),
            (false, true, false, false, false, "display asleep"),
            (false, false, true, false, false, "machine sleeping"),
            (false, false, false, true, false, "declared away")
        ]
        for item in cases {
            let actual = AppCoordinator.breakReminderReachesScreen(
                screenLocked: item.locked, displayAsleep: item.asleep,
                machineSleeping: item.sleeping, away: item.away)
            expect(actual == item.expected,
                   "break reminder channel for \(item.label) expected HUD=\(item.expected), got \(actual)",
                   &problems)
        }
        return problems
    }
}
